SELECT SV.FACULTY_ID
FROM SUPERVISE SV,STUDENT S,CONDUCT_ANALYZE CA
WHERE SV.STUDENT_ID=S.STUDENT_ID AND S.USER_ID= CA.USER_ID
GROUP BY SV.FACULTY_ID
HAVING COUNT(DISTINCT CA.USER_ID)=
 (SELECT MIN(USID)
  FROM (SELECT COUNT(DISTINCT CA1.USER_ID) AS USID
        FROM SUPERVISE SV1,STUDENT S1,CONDUCT_ANALYZE CA1
        WHERE SV1.STUDENT_ID=S1.STUDENT_ID AND S1.USER_ID= CA1.USER_ID
        GROUP BY SV1.FACULTY_ID
        HAVING COUNT(DISTINCT CA1.USER_ID) IS NOT NULL));
